analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    no_leading_underscores_for_local_identifiers: ignore
    invalid_annotation_target: ignore
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - avoid_print
    - avoid_empty_else
    - prefer_final_fields
    - unnecessary_statements
    - avoid_returning_null_for_future
