name: deun
description: "Share Expenses with Friends"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  collection: ^1.18.0
  firebase_core: ^3.10.1
  firebase_messaging: ^15.2.1
  flutter:
    sdk: flutter
  flutter_form_builder: ^9.3.0
  flutter_local_notifications: ^18.0.1
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  form_builder_extra_fields: ^11.1.0
  form_builder_validators: ^11.0.0
  go_router: ^14.4.1
  google_sign_in: ^6.2.2
  grouped_list: ^6.0.0
  intl: any
  msix: ^3.16.8
  riverpod_annotation: ^2.6.1
  sign_in_with_apple: ^6.1.4
  supabase_auth_ui: ^0.5.1
  supabase_flutter: ^2.8.0
  universal_html: ^2.2.4
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.11
  build_web_compilers: ^4.0.10
  flutter_launcher_icons: ^0.14.2

msix_config:
  display_name: Deun
  msix_version: 1.0.0.2
  protocol_activation: https # Add the protocols to activate the app
  app_uri_handler_hosts: www.deun.app, deun.app # Add the app uri handler hosts. You can't use patterns here.

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/icon/icon-512.png
