name: deun
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  collection: ^1.18.0
  flutter:
    sdk: flutter
  flutter_form_builder: ^9.3.0
  flutter_localizations:
    sdk: flutter
  form_builder_extra_fields: ^10.2.0
  form_builder_validators: ^11.0.0
  go_router: ^14.4.1
  google_sign_in: ^6.2.2
  grouped_list: ^6.0.0
  intl: any
  supabase_auth_ui: ^0.5.1
  supabase_flutter: ^2.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  generate: true
  uses-material-design: true
