// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEPxovASHn7LYzAdX3_U04HGuwqUkPmKg',
    appId: '1:772955736601:web:726b71f0a311d9a7843888',
    messagingSenderId: '772955736601',
    projectId: 'deun-66067',
    authDomain: 'deun-66067.firebaseapp.com',
    storageBucket: 'deun-66067.firebasestorage.app',
    measurementId: 'G-Q5WZXQZSJ7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClBcdHlPEAO7TY84_o4JtwKkMa78_AKdM',
    appId: '1:772955736601:android:065d9a6372018367843888',
    messagingSenderId: '772955736601',
    projectId: 'deun-66067',
    storageBucket: 'deun-66067.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAW9OX424Pu6TTC3Vy3kxN5P7PB1By7tBU',
    appId: '1:772955736601:ios:f1ecccfe32d53686843888',
    messagingSenderId: '772955736601',
    projectId: 'deun-66067',
    storageBucket: 'deun-66067.firebasestorage.app',
    iosBundleId: 'com.example.deun',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAW9OX424Pu6TTC3Vy3kxN5P7PB1By7tBU',
    appId: '1:772955736601:ios:f1ecccfe32d53686843888',
    messagingSenderId: '772955736601',
    projectId: 'deun-66067',
    storageBucket: 'deun-66067.firebasestorage.app',
    iosBundleId: 'com.example.deun',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEPxovASHn7LYzAdX3_U04HGuwqUkPmKg',
    appId: '1:772955736601:web:9f4fadd871e096d4843888',
    messagingSenderId: '772955736601',
    projectId: 'deun-66067',
    authDomain: 'deun-66067.firebaseapp.com',
    storageBucket: 'deun-66067.firebasestorage.app',
    measurementId: 'G-VXF0G2WP6L',
  );
}
